<?php
$javacode             = $block->panelHelper->getJavaCode(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$classes              = $block->panelHelper->getClasses(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$styles               = $block->panelHelper->getStyles(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$sketchEnableStatus   = $block->panelHelper->getSketchEnableStatus(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$photoEnableStatus    = $block->panelHelper->getPhotoEnableStatus(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$emptySketchUrl       = $block->panelHelper->emptyUrl("sketch", \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$emptyPhotoUrl        = $block->panelHelper->emptyUrl("photo", \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$moduleIcons          = $block->panelHelper->getEnableModuleIcons(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$searchCode           = $block->getRequest()->getParam('search_uid');
$baseUrl              = $block->getBaseUrl();
$sketchIconUrl        = $block->getSketchIcon(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$photoIconUrl         = $block->getPhotoIcon(\Magento\Store\Model\ScopeInterface::SCOPE_STORE);
?>

<script type="text/x-magento-init">
    {
        "*":{
            "impresee":{},
            "Jcrop":{}
        }
    }
</script>
<script type="text/javascript">
require(["jquery"], function($){
    <?php echo $javacode . "\n"?>
    $(window).bind('resize', function (e) {
      // user custom javascript/jquery code (on bind/resize to adjust on size change)
        <?php echo $javacode?>
    });
    /**
     * prevent display Impresee Buttons when the search features isn't enabled,
     * or search service URL isn't configurated
     */
    if ( (<?php echo $sketchEnableStatus?> == 1) && (<?php echo $emptySketchUrl?> !=1 ) && (<?php echo $moduleIcons?>  == 1) ){
        $("#ImpreseeSketch").css('display', $('input[id*="search"][name="q"]').css('display'));
    }else{
        $("#ImpreseeSketch").css('display', "none");
    }
    if ((<?php echo $photoEnableStatus?> == 1 ) && (<?php echo $emptyPhotoUrl?> !=1) && (<?php echo $moduleIcons?> == 1)){
      $("#ImpreseePhoto").css('display', $('input[id*="search"][name="q"]').css('display'));
    }else{
      $("#ImpreseePhoto").css('display', "none");
    }

});
</script>
<!-- user custom styles -->
<style>
    <?php echo $styles?>
</style>
    <!-- our frontend buttons -->
    <img id="ImpreseeSketch" class="impresee-sketch-button impreseeButton <?php echo $classes?>" src="<?php echo $sketchIconUrl?>"  />
    <img id="ImpreseePhoto" class="impresee-photo-button impreseeButton <?php echo $classes?>" src="<?php echo $photoIconUrl?> " />
    <!-- hidden file input tag-->
    <input type="file" accept="images/jpeg;capture=camera" id="imguploadphoto" style="display:none"/>
    <div id="modalDiv">
        <div id="canvasDiv" style="display:none; margin: 0 auto">
        <!-- canvas will go inside this-->
        </div>
    </div>
<script type="text/javascript">

    /**
     * Make Impresee Image search
     * @param string type , type of search
     * @param string data , base64 string of an image/sketch
     */
    function makeSearch(type, data){
        var resultsUrl  = "<?php echo $baseUrl?>" + "impresee/Results/Search";
        var searchUrl  = "<?php echo $baseUrl?>" + "impresee/Results/Impreseesearch";
        var xhr = new XMLHttpRequest();
        var requestJson = {};
        //kind of search
        requestJson["type"] = type;
        requestJson["data"] = data;
        requestJson["url"]  = resultsUrl;
        xhr.open("POST", searchUrl, true);
        xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
        xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
        xhr.send(JSON.stringify(requestJson));
        xhr.onload = function() {
            var responseSearch = JSON.parse(xhr.responseText);
            window.location.replace(responseSearch["url"]);
        }
    }
    /**
     * Send to Impresee when someone clicks on a product after an Impresee search
     * @param string type , type of search
     * @param int rank , position of product on similarity rank
     */
    function sendClick(type, rank){
        var clickUrl  = "<?php echo $baseUrl?>" + "impresee/Results/SendClick";
        var search_uid  = "<?php echo $searchCode?>";
        var xhr = new XMLHttpRequest();
        var requestJson = {};
        requestJson["type"] = type;
        requestJson["search_uid"] = search_uid;
        requestJson["rank"]  = rank;
        xhr.open("POST", clickUrl, true);
        xhr.setRequestHeader('Content-Type', 'application/json; charset=UTF-8');
        xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");
        xhr.send(JSON.stringify(requestJson));
    }
</script>
