<script type="text/javascript">
    window._wsee_logged_customer = {
        'id':'<?php echo $block->customerData->getId(); ?>' || '',
    }
    window._wsse_page_type_event = '<?php echo $block->getCurrentPageEvent(); ?>';
    let impreseeScreen = '<?php echo $block->screen; ?>';
    
    function _wsse_register_event(extraData, event) {
        const impreseeRegisterUrl = '<?php echo $block->requestsHelper->getRegisterEventsUrl(); ?>';
        const impreseeCode = '<?php echo $block->codesHelper->getImpreseeUuid(\Magento\Store\Model\ScopeInterface::SCOPE_STORE) ?  $block->codesHelper->getImpreseeUuid(\Magento\Store\Model\ScopeInterface::SCOPE_STORE) : ''; ?>';
        
        let impreseeAction = '<?php echo $block->codesHelper->getRegisterEventsAction(); ?>';
        let urlParams = new URLSearchParams(window.location.search || '?' + window.location.hash.split('?')[1]);
        let from_impresee_text = urlParams.get('source_impresee') || '';
        let from_impresee_visual = urlParams.get('seecd') || '';
        let data = 'a=' + encodeURIComponent(impreseeAction);
        data += '&evt=' + encodeURIComponent(event);
        data += '&fi=' + encodeURIComponent(from_impresee_text);
        data += '&fiv=' + encodeURIComponent(from_impresee_visual);
        data += '&cusid=' + encodeURIComponent(_wsee_logged_customer.id);
        data += extraData;

        if (impreseeCode) {
            var xmlHttp = new XMLHttpRequest();
            xmlHttp.withCredentials = true;
            xmlHttp.open( "GET", impreseeRegisterUrl + impreseeCode + '?' + data, true );
            xmlHttp.send( null );
        }
    }

    let impreseeData = '';
    if (window._wsse_page_type_event === 'VIEW_PRODUCT') {
        const _wsee_productSku = '<?php echo $block->getCurrentProduct() ? $block->getCurrentProduct()->getSku() : ''; ?>';
        const _wsee_productId = '<?php echo $block->getCurrentProduct() ? $block->getCurrentProduct()->getId() : ''; ?>';
        const _wsee_productName = '<?php echo $block->getCurrentProduct() ? $block->getCurrentProduct()->getName() : ''; ?>';
        impreseeData += '&pid=' + encodeURIComponent(_wsee_productId);
        impreseeData += '&sku=' + encodeURIComponent(_wsee_productSku);
        impreseeData += '&pna=' + encodeURIComponent(_wsee_productName);
    }
    else if (window._wsse_page_type_event === 'VIEW_CATEGORY') {
        const _wsee_category = '<?php echo $block->getCurrentCategory() ? $block->getCurrentCategory()->getName() : ''; ?>';
        const _wsee_categoryId = '<?php echo $block->getCurrentCategory() ? $block->getCurrentCategory()->getId() : ''; ?>';
        const _wsee_categoryUrl = '<?php echo $block->getCurrentCategory() ? $block->getCurrentCategory()->getUrl() : ''; ?>';
        impreseeData += '&cat=' + encodeURIComponent(_wsee_category);
        impreseeData += '&catid=' + encodeURIComponent(_wsee_categoryId);
        impreseeData += '&caturl=' + encodeURIComponent(_wsee_categoryUrl);
    }
    else if (impreseeScreen) {
        impreseeData += '&scr=' + encodeURIComponent(impreseeScreen);
    }
    impreseeData += '<?php echo $block->getBaseUrlData(); ?>';

    _wsse_register_event(impreseeData, window._wsse_page_type_event);
</script>
